# Generated by Django 4.2.1 on 2023-05-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='auhtor',
            new_name='author',
        ),
    ]
