# Generated by Django 4.2.1 on 2023-05-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_rename_auhtor_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
